# Generated by Django 6.0.6 on 2026-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('building', models.CharField(default='Main Building', max_length=100)),
                ('floor', models.CharField(default='Ground Floor', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('room_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('lab', 'Laboratory'), ('seminar_room', 'Seminar Room'), ('conference_room', 'Conference Room'), ('smart_classroom', 'Smart Classroom')], default='lecture_hall', max_length=30)),
                ('has_projector', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['building', 'room_number'],
            },
        ),
    ]
